export const screenName = {
  AUTHENTICATION_NAVIGATOR: "authentication navigator",
  MAIN_NAVIGATOR: "main navigator",
  LOGIN: "login",
  REGISTER: "register",
  FORGOT_PASSWORD: "forgot password",
  POSTING_PRODUCT_FORM: 'posting product',
  POSTING_MANAGEMENT: 'manage post',
  ORDERED_MANAGEMENT: 'ordered management',
  USER_CART: 'user cart',
  HOME: "home",
  MESSAGE: "message",
  PRODUCT: "product",
  ACCOUNT: "account",
  PRODUCT_DETAIL: "product detail",
  PAYMENT_SUCCESS: "payment success",
  ORDER_DETAIL: "order detail",
  ORDER_CONFIRMATION: "order confirmation",
}